language: node_js

matrix:
  fast_finish: true
  include:
    - env: TEST='minimal'
      node_js: '7'
    - env: TEST='normal'
      node_js: '7'
  allow_failures:
    - env: TEST='normal'

addons:
  sauce_connect:
    username: 'iyegoroff-5'
    no_ssl_bump_domains: all
  jwt:
    secure: >
      UukZRNFKzNbfm0gKBXp3lmr9H/B+lOPQ0hwwe8h5hiSy+qZJZJ+taAIDDmAujF+OwsLQg+otQojeIdUq0lXyXwAjEqoJmt9KHRw66hTSon6gE/sur
      uY5whvb+DuCvq95w17AuSeZYwUZ6bjl+JQE1xWd4QuaCAviZv/Ddv5rpBmmO6eax4wDZPKs6MTCHTu1KWZNNh/R75eUH5IdqjJVnR2fpI/5F2F/Is
      +e84eSV1auIjbRJo6LkpeSOKrqFBHVUBFinf45M8bp33GmGlduKRaGbtkdyNF7d3ScrYz+w6FOFrn0nzYpraNhUNgPmthj0p6TZxpYUlezg7T7QV5
      Y0r5KZUYx5mPrxwsVBZTktLFJB9vs+SpBZ2f0jRfZTlHtSZHGbBhBSXIJo+kwomst4qoGD7p5WGdPi43DmEpGLc5KCPmFHmxvSjrrUYXL2WqVOdwD
      mLEDRab/qDTSFYj+ABzwlrf/OoAbbEQ2jJUnd5h+PtaYszWAb5GVG3MG1VcqylPm4Jt+BHeAKffmCDfGwN72ixKM32aRLJUpHdljBBUkp/nKz6KxE
      AenW/ALZG195vTgHKDy6YayDAhEhT3j8uS5lceyXASvs5lpM36/9fFFljnF6c3P3KFlY/AZAGgIiUrzkm2R1SsT7R59uh7J44ElTw3mUSp7tJCuI9
      e9iB4=


branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

before_deploy:
  cp ./dist/kendo-multi-calendar.min.js ./public/kendo-multi-calendar.min.js

deploy:
  - provider: npm
    email: iegoroff@gmail.com
    api_key:
      secure: >
        Ws0lVPKRNnSeiBf2XAjqGJOqhTaMfZf4Fjc9UdwQTAM7z+z1RpBqf5nTCQPIqu9x3cspP6CQPzArzMQ8hEHdFfUzTNQrqIiO6m/KxbX48Or4zXv
        2zwDhhr30EjdH56af68J+NogwrQsjDqKDBSwMSYYfuSBw4gzMGn8KH73Km83eW6fNuop3vd+Mej2uUxWg3V6XjmbEfXFponVTEkV1X43XXEBc2N
        dbBtnfFAyKRXH1mHQF/e/1pRNWDgOfObvqypzpvBoZJGBBOeRikYpv986D1juMWTHDTOxin724OP5i0HbuoF3BtmjURBnovOfMUASqp/IpH39cn
        TxqoMnjbQuh7znZAC7Zie9EswVo9JAluDS0thqYCZzaSfUdtgZN26xayBcAADrJ7QwrJnABG/d8XlawS7i7vtwhfVQtYOGHD9I/MSgqsDqDAFv7
        y/nbAbtLGrxsD3lFDQtQGua4ZQU8Dzuya7mDjQTnK+8U0jm7DSBiAq5Q5VGzY5mHHpA7+G4uNzzFRHBMonf76Px19pvZqlMiKqTE6fRTFlWt32d
        onAtGm73B9EhBQPTe39qWMjipGjFqRZiVCNBwPKo3TDlyCJbRFCPkhEsRW+BvdJo5aizDSQhtKt+JcfC2ZOhuAH6CR8TJACVmS6h/frNPV1vNw+
        1/ZzFhZfB7RwV0TLc=
    skip_cleanup: true
    on:
      tags: true
      condition: $TEST == 'minimal'
  - provider: surge
    project: ./public/
    domain: kendo-multi-calendar.surge.sh  
    skip_cleanup: true
    on:
      tags: true
      condition: $TEST == 'minimal'

before_script:
  npm run build

script:
  - if [[ $TEST == 'minimal' ]]; then npm run lint && npm run test:ci:minimal; fi
  - if [[ $TEST == 'normal' ]]; then npm run test:ci:normal; fi
after_script:
  if [[ $TEST == 'minimal' ]]; then npm run coverage; fi
